server:
  port:8080

# Sqlite
spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/sql/stgd_voice.db # 改为数据库路径
    driver-class-name: org.sqlite.JDBC

# MyBatis-Plus
##################### mybatis-plus配置 ######################
mybatis-plus:
  # 包扫描路径(当前项目的实体类所在位置。别名包扫描路径，通过该属性可以给包中的类注册别名，多个路径用逗号分割)
  type-aliases-package: com.stgd.voice.stgdvoice.entity
  # xml扫描，多个目录用逗号或者分号分隔(告诉 Mapper 所对应的 XML 文件位置)
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    # 允许在resultType="map"时映射null值
    call-setters-on-nulls: true
    # 打印sql出来(包括执行结果)
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键类型 AUTO:"数据库ID自增"
      # INPUT:"用户输入ID",
      # ID_WORKER:"全局唯一ID (数字类型唯一ID)",
      # UUID:"全局唯一ID UUID";
      id-type: auto
      # 字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      # 数据库类型
      db-type: MYSQL
      # 逻辑删除配置
      # 删除前
      logic-not-delete-value: 0
      # 删除后
      logic-delete-value: 1
      # 数据库表名的前缀
